"""empty message

Revision ID: 24526f25b129
Revises: 05a8e64be6bb
Create Date: 2017-09-23 22:54:46.870318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24526f25b129'
down_revision = '05a8e64be6bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(length=255), nullable=True),
    sa.Column('dish_url', sa.String(length=255), nullable=True),
    sa.Column('dish_bitmap', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dishes')
    # ### end Alembic commands ###
