"""empty message

Revision ID: 45d8bbfdac40
Revises: b93493488bbc
Create Date: 2017-09-24 05:06:44.719679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d8bbfdac40'
down_revision = 'b93493488bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_auth', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_auth')
    # ### end Alembic commands ###
