"""empty message

Revision ID: 465745427642
Revises: 628760ff157d
Create Date: 2017-10-16 01:52:35.698533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '465745427642'
down_revision = '628760ff157d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dish_bitmap')
    op.drop_column('users', 'dish_url')
    op.drop_column('users', 'dish_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dish_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('dish_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('dish_bitmap', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
