"""empty message

Revision ID: 628760ff157d
Revises: 2ca1c30cd815
Create Date: 2017-09-24 07:25:31.283045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628760ff157d'
down_revision = '2ca1c30cd815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_fitted', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_fitted')
    # ### end Alembic commands ###
