"""empty message

Revision ID: b93493488bbc
Revises: f62d2c702011
Create Date: 2017-09-24 04:19:27.218620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b93493488bbc'
down_revision = 'f62d2c702011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('fname', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('lname', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('num_of_dishes', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('num_of_neg_dishes', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('num_of_neg_recipes', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('num_of_pos_dishes', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('num_of_pos_recipes', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    op.drop_column('users', 'num_of_pos_recipes')
    op.drop_column('users', 'num_of_pos_dishes')
    op.drop_column('users', 'num_of_neg_recipes')
    op.drop_column('users', 'num_of_neg_dishes')
    op.drop_column('users', 'num_of_dishes')
    op.drop_column('users', 'lname')
    op.drop_column('users', 'fname')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
