"""empty message

Revision ID: f62d2c702011
Revises: 24526f25b129
Create Date: 2017-09-24 02:41:31.828988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62d2c702011'
down_revision = '24526f25b129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users',
    sa.Column('prev_dish', sa.PickleType(), nullable=True))
    op.add_column('users',
    sa.Column('eval_dish_ids', sa.PickleType(), nullable=True))
    op.add_column('users',
    sa.Column('X', sa.PickleType(), nullable=True))
    op.add_column('users',
    sa.Column('y', sa.PickleType(), nullable=True))
    op.add_column('users',
    sa.Column('clf', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'prev_dish')
    op.drop_column('users', 'eval_dish_ids')
    op.drop_column('users', 'X')
    op.drop_column('users', 'y')
    op.drop_column('users', 'clf')
    # ### end Alembic commands ###
